apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-chat-template
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fullnameOverride }}
    app.kubernetes.io/managed-by: Helm
data:
  chat_template.b64: |
{{ .Values.chatTemplateB64 | indent 4 }}
