apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimqwen36llama.fullname" . }}
  labels:
    io.kompose.service: {{ include "aimqwen36llama.fullname" . }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ include "aimqwen36llama.fullname" . }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    io.kompose.service: {{ include "aimqwen36llama.fullname" . }}
